### PR TITLE
Enh: retry on IO error: also give failure reason in warning call and com...

### PR DESCRIPTION
**Pull request by gst**
...ments

And even better test:

+ few added asserts.
+ use mock with wraps around logger (so to also see the message in console output)

### CODE REVIEW

**Comment by Seb-Solon** [comment]
We should fix test propely fisrt. They just return ok for now

**Comment by Seb-Solon** [comment]
https://github.com/shinken-monitoring/mod-booster-nrpe/commit/518ea703bfa994c03e249c13257bedcf309b8c0a. The fact you rename the directory break the setup. If you change the directory for this test then you should adapt the script. It is not really good because all script for all module should be the same :(

**Comment by gst** [comment]
@Seb-Solon 
`break the setup.` ...  I guess you talk about `setup_module_test.sh` ? or what else "setup" ?

but the fact is that this *module* doesn't need shinken/test directory at all.. it only need shinken package itself, obviously as it import it. Which is great ;)

**Comment by gst** [comment]
> We should fix test propely fisrt. They just return ok for now

fix test properly ? but what do you talk about exactly ^? the tests just pass successfully, I don't get what you mean by "return ok for now"  ;)

**Comment by Seb-Solon** [comment]
The setup module is generic for all module. Of course tests may not require it but IMO we may keep that. The shinken/test is cleaned btw, only module import and shinken_test are keep so that your test can use it (like inherit from ShinkenTest). I was planning to tag this after this PR but I think we should at least fix test to that the tag is fine.

**Comment by gst** [comment]
I had not check travis.. and effectively there is a problem there.. damn obviously. Should have checked it faster.. my bad so ;) Gonna see that.. 

For shinken_test and so : hmm.. the structure is now more cleaned yes, the structure ;)  But I won't make this module tests classes to subclass ShinkenTest if they don't need to ;)

**Comment by gst** [comment]
about:
> The setup module is generic for all module.

well.. let's say that it has been used in some shinken module here and there.. though not necessarily in a generic way..
but I don't like this setup_module_test.sh at all in fact, for me it's completely temporary ; it's quite over-complex ;  sooner or later we should have some real/good setup.py for each shinken module that when we want to test it we would only have to do (under a virtualenv) "python setup.py install" and all should be put in place by the setup.py, modulo eventual other very specific setup for the tests.
is it the way we want to go in some time in the future ?

**Comment by Seb-Solon** [comment]
Well, good thing to debate yeah. I tried to have a consitent temporary solution. I agree that setup.py should be better for all modules, but it should impact the moduIe itself IMO.

Anyway my point was just to get something working for tagging no matter how :)

**Comment by gst** [comment]
got it ;)

**Comment by gst** [comment]
here it is :p (pfouu)

**Comment by gst** [comment]
@Seb-Solon ..

**Comment by Seb-Solon** [comment]
LGTM

**Pull request merged**
